apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: multi-app-updater
spec:
  namespace: argocd
  writeBackConfig:
    method: "argocd"
  applicationRefs:
    - namePattern: "courier"
      images:
        - alias: "courier"
          imageName: "ghcr.io/mackmarton/courier"
          manifestTargets:
            helm:
              name: "ghcr.io/mackmarton/courier"
              tag: "image.tag"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            pullSecret: "pullsecret:argocd/ghcr-login-secret"
    - namePattern: "logistics"
      images:
        - alias: "logistics"
          imageName: "ghcr.io/mackmarton/logistics"
          manifestTargets:
            helm:
              name: "ghcr.io/mackmarton/logistics"
              tag: "image.tag"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            pullSecret: "pullsecret:argocd/ghcr-login-secret"
    - namePattern: "orders"
      images:
        - alias: "orders"
          imageName: "ghcr.io/mackmarton/orders"
          manifestTargets:
            helm:
              name: "ghcr.io/mackmarton/orders"
              tag: "image.tag"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            pullSecret: "pullsecret:argocd/ghcr-login-secret"
    - namePattern: "tracking"
      images:
        - alias: "tracking"
          imageName: "ghcr.io/mackmarton/tracking"
          manifestTargets:
            helm:
              name: "ghcr.io/mackmarton/tracking"
              tag: "image.tag"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            pullSecret: "pullsecret:argocd/ghcr-login-secret"
    - namePattern: "api-gateway"
      images:
        - alias: "api-gateway"
          imageName: "ghcr.io/mackmarton/api-gateway"
          manifestTargets:
            helm:
              name: "ghcr.io/mackmarton/api-gateway"
              tag: "image.tag"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            pullSecret: "pullsecret:argocd/ghcr-login-secret"
    - namePattern: "client-ui"
      images:
        - alias: "client-ui"
          imageName: "ghcr.io/mackmarton/client-ui"
          manifestTargets:
            helm:
              name: "ghcr.io/mackmarton/client-ui"
              tag: "image.tag"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            pullSecret: "pullsecret:argocd/ghcr-login-secret"
    - namePattern: "logistics-ui"
      images:
        - alias: "logistics-ui"
          imageName: "ghcr.io/mackmarton/logistics-ui"
          manifestTargets:
            helm:
              name: "ghcr.io/mackmarton/logistics-ui"
              tag: "image.tag"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            pullSecret: "pullsecret:argocd/ghcr-login-secret"
    - namePattern: "courier-ui"
      images:
        - alias: "courier-ui"
          imageName: "ghcr.io/mackmarton/courier-ui"
          manifestTargets:
            helm:
              name: "ghcr.io/mackmarton/courier-ui"
              tag: "image.tag"
          commonUpdateSettings:
            updateStrategy: "newest-build"
            pullSecret: "pullsecret:argocd/ghcr-login-secret"