apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logistics.fullname" . }}
  labels:
    {{- include "logistics.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "logistics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "logistics.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.config.serverPort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "logistics.fullname" . }}-config
        env:
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.datasource.passwordSecretName | default (printf "%s-db-secret" (include "logistics.fullname" .)) }}
              key: {{ .Values.config.datasource.passwordSecretKey }}
        - name: OPEN_ROUTE_SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.api.openRouteService.keySecretName }}
              key: {{ .Values.config.api.openRouteService.keySecretKey }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
