replicaCount: 2

image:
  repository: ghcr.io/mackmarton/courier-ui
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: github-auth

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 32Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

config:
  viteApiBaseUrl: https://api.micro-futar.hu
