spring:
  application:
    name: orders
  profiles:
    active: ${SPRING_PROFILE}
  jpa:
    generate-ddl: false
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

server:
  port: ${SERVER_PORT}
