# Az argocd-server IngressRoute-ja az argocd namespace-ben van, a TLS
# secretnek is itt kell élnie.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: micro-futar-tls
  namespace: argocd
spec:
  secretName: micro-futar-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argo.micro-futar.hu
