apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-client-secret-prod
  namespace: micro-futar-apps-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: api-gateway-client-secret-prod
    creationPolicy: Owner
  data:
  - secretKey: CLIENT_SECRET # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: api-gateway-client-secret-prod # A Vault-beli útvonal
      property: CLIENT_SECRET # A Vault-beli kulcs
