apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-login-secret
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr-login-secret
    creationPolicy: Owner
  data:
  - secretKey: docker-password  # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: ghcr-login-secret # A Vault-beli útvonal
      property: docker-password # A Vault-beli kulcs
  - secretKey: docker-server  # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: ghcr-login-secret # A Vault-beli útvonal
      property: docker-server  # A Vault-beli kulcs
  - secretKey: docker-username  # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: ghcr-login-secret # A Vault-beli útvonal
      property: docker-username  # A Vault-beli kulcs