apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets-dev
  namespace: micro-futar-services-dev
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-secrets-dev
    creationPolicy: Owner
  data:
  - secretKey: DBPASSWORD # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: keycloak-secrets-dev # A Vault-beli útvonal
      property: DBPASSWORD # A Vault-beli kulcs
  - secretKey: ADMINPASSWORD # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: keycloak-secrets-dev # A Vault-beli útvonal
      property: ADMINPASSWORD # A Vault-beli kulcs