apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: logistics-db-secret-prod
  namespace: micro-futar-apps-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: logistics-db-secret-prod
    creationPolicy: Owner
  data:
  - secretKey: password # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: logistics-db-secret-prod # A Vault-beli útvonal
      property: password # A Vault-beli kulcs
