apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-route-service-secret-dev
  namespace: micro-futar-apps-dev
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: open-route-service-secret-dev
    creationPolicy: Owner
  data:
  - secretKey: KEY # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: open-route-service-secret-dev # A Vault-beli útvonal
      property: key # A Vault-beli kulcs