apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-route-service-secret-prod
  namespace: micro-futar-apps-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: open-route-service-secret-prod
    creationPolicy: Owner
  data:
  - secretKey: KEY # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: open-route-service-secret-prod # A Vault-beli útvonal
      property: KEY # A Vault-beli kulcs
