apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-db-secret-dev
  namespace: micro-futar-apps-dev
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: orders-db-secret-dev
    creationPolicy: Owner
  data:
  - secretKey: PASSWORD # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: orders-db-secret-dev # A Vault-beli útvonal
      property: password # A Vault-beli kulcs