apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-auth-secret
  namespace: micro-futar-services-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-auth-secret
    creationPolicy: Owner
  data:
  - secretKey: postgresql-password # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: postgres-auth-secret # A Vault-beli útvonal
      property: postgresql-password # A Vault-beli kulcs
