apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-auth-secret
  namespace: micro-futar-services-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: redis-auth-secret
    creationPolicy: Owner
  data:
  - secretKey: REDIS_PASSWORD # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: redis-auth-secret # A Vault-beli útvonal
      property: REDIS_PASSWORD # A Vault-beli kulcs
