apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: micro-futar-apps-dev
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-k8s-secret
    creationPolicy: Owner
  data:
  - secretKey: TEST_KEY # Ez lesz a kulcs a K8s Secretben
    remoteRef:
      key: test # A Vault-beli útvonal
      property: test # A Vault-beli kulcs