apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders.fullname" . }}-config
  labels:
    {{- include "orders.labels" . | nindent 4 }}
data:
  DATASOURCE_URL: {{ .Values.config.datasource.url | quote }}
  DATASOURCE_USERNAME: {{ .Values.config.datasource.username | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafka.bootstrapServers | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  SPRING_PROFILE: {{ .Values.config.springProfile | quote }}
  KEYCLOAK_URL: {{ .Values.config.keycloak.url | quote }}
  LOCATION_REGION_TOPIC: {{ .Values.kafka.topics.location_region_topic | quote }}
  LOCATION_COUNTRY_TOPIC: {{ .Values.kafka.topics.location_country_topic | quote }}
  LOCATION_CITY_TOPIC: {{ .Values.kafka.topics.location_city_topic | quote }}
  COUNTRY_PRICE_TOPIC: {{ .Values.kafka.topics.country_price_topic | quote }}
  PACKAGE_SIZE_TOPIC: {{ .Values.kafka.topics.package_size_topic | quote }}
  SHIPMENT_TOPIC: {{ .Values.kafka.topics.shipment_topic | quote }}
