apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "client-ui.fullname" . }}-config
  labels:
    {{- include "client-ui.labels" . | nindent 4 }}
data:
  VITE_API_BASE_URL: {{ .Values.config.viteApiBaseUrl | quote }}
