replicaCount: 3

image:
  repository: ghcr.io/mackmarton/orders
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: github-auth

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8081"
  prometheus.io/path: "/actuator/prometheus"

config:
  serverPort: 8081
  springProfile: prod
  datasource:
    url: jdbc:postgresql://postgres-postgresql.micro-futar-services-prod:5432/orders_db
    username: orders_db
    passwordSecretName: orders-db-secret-prod
    passwordSecretKey: password
  kafka:
    bootstrapServers: kafka.micro-futar-services-prod:9092
  keycloak:
    url: https://auth.micro-futar.hu

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

kafka:
  topics:
    location_region_topic: location-regions
    location_country_topic: location-countries
    location_city_topic: location-cities
    country_price_topic: country-prices
    package_size_topic: package-sizes
    shipment_topic: shipments