server:
  port: ${SERVER_PORT}

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILE}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/micro-futar-realm
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, email, offline_access
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay
          routes:
            - id: order-service
              uri: ${ORDER_SERVICE_URI}
              predicates:
                - Path=/api/orders/**
              filters:
                - RewritePath=/api/orders/(?<segment>.*), /api/$\{segment}
            - id: tracking-service
              uri: ${TRACKING_SERVICE_URI}
              predicates:
                - Path=/api/tracking/**
              filters:
                - RewritePath=/api/tracking/(?<segment>.*), /api/$\{segment}
            - id: logistics-service
              uri: ${LOGISTICS_SERVICE_URI}
              predicates:
                - Path=/api/logistics/**
              filters:
                - RewritePath=/api/logistics/(?<segment>.*), /api/$\{segment}
            - id: courier-service
              uri: ${COURIER_SERVICE_URI}
              predicates:
                - Path=/api/courier/**
              filters:
                - RewritePath=/api/courier/(?<segment>.*), /api/$\{segment}
