spring:
  jpa:
    generate-ddl: true
kafka:
  topics:
    package-size-topic: package-sizes
    shipment-topic: shipments
    depo-topic: depos
    shipment-route-courier-topic: shipment-route-couriers
    shipment-route-topic: shipment-routes
    courier-topic: couriers
    vehicle-topic: vehicles