apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "courier-ui.fullname" . }}-config
  labels:
    {{- include "courier-ui.labels" . | nindent 4 }}
data:
  VITE_API_BASE_URL: {{ .Values.config.viteApiBaseUrl | quote }}
