replicaCount: 1

image:
  repository: tracking
  pullPolicy: Never
  tag: "latest"

service:
  type: NodePort
  port: 8081
  targetPort: 8081

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

config:
  serverPort: 8081
  springProfile: local
  datasource:
    url: jdbc:postgresql://postgres-db-postgresql.micro-futar-services:5432/tracking_db
    username: tracking_db
    passwordSecretName: tracking-db-secret
    passwordSecretKey: password
  kafka:
    bootstrapServers: kafka.micro-futar-services:9092
  keycloak:
    url: http://localhost:8090
