replicaCount: 1

image:
  repository: ghcr.io/mackmarton/tracking
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: github-auth

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

autoscaling:
  enabled: false

config:
  serverPort: 8080
  springProfile: dev
  datasource:
    url: jdbc:postgresql://postgres-db-postgresql.micro-futar-services-dev:5432/tracking_db
    username: tracking_db
    passwordSecretName: tracking-db-secret-dev
    passwordSecretKey: PASSWORD
  kafka:
    bootstrapServers: kafka-futar.micro-futar-services-dev:9092
  keycloak:
    url: http://keycloak-dev:8080
  mail:
    host: smtp.rackhost.hu
    port: 587
    username: noreply@micro-futar.hu
    from: noreply@micro-futar.hu
    smtpAuth: true
    sslEnabled: false
    starttlsEnabled: true
    passwordSecretName: smtp-secret-dev
    passwordSecretKey: PASSWORD
  notification:
    trackingPageUrl: http://localhost:8070/portal/tracking

kafka:
  topics:
    location_country_topic: location-countries
    location_city_topic: location-cities
    shipment_topic: shipments
    shipment_notification_topic: shipment-notifications
    depo_topic: depos
    shipment_route_topic: shipment-routes